export const BUSINESS_TYPES = [
  "Retail",
  "Wholesale",
  "Service",
  "Manufacturing",
  "Distributor",
  "Kirana & Supermarket",
  "Hardware, Paints & Sanitary",
  "Garments, Footwear & Fashion",
  "Pharmacy & Healthcare",
  "Restaurant, Cafe & Dhaba",
  "Electronics, Mobile & Repairs",
  "Salon, Spa & Beauty Care",
  "Automobile & Garage Services",
  "Jewellery & Goldsmith",
  "Building Materials & Construction",
];
