import React, { useState } from "react";
import { MessageCircle } from "lucide-react";
import api from "../services/api"; // Fixed import path

export default function WhatsappSender({ bill }) {
  const [loading, setLoading] = useState(false);

  const handleSend = async () => {
    if (!bill.customerMobile) {
      alert("Customer mobile number is missing for this bill!");
      return;
    }

    setLoading(true);
    try {
      let mobile = bill.customerMobile.replace(/\D/g, "");
      if (mobile.length === 10) mobile = "91" + mobile;

      // Fetch dynamic message with Payment Link from Backend
      const response = await api.post("/api/whatsapp/send-invoice", {
        billId: bill._id,
        mobileNumber: mobile
      });

      // Use the preview message generated by backend, or fallback to default
      const message = response.data?.preview || response.preview || `Hello ${bill.customerName},\n\nYour invoice *${bill.billNumber || bill.billNo}* for amount *₹${(bill.total || bill.finalAmount || 0).toLocaleString()}* has been generated.\n\nThank you for your business!`;

      const url = `https://wa.me/${mobile}?text=${encodeURIComponent(message)}`;
      window.open(url, "_blank");
    } catch (error) {
      console.error("Failed to generate WhatsApp message", error);
      alert("Failed to generate WhatsApp link. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button type="button" onClick={handleSend} disabled={loading} className="p-2 hover:bg-green-100 rounded-lg text-green-600 transition disabled:opacity-50" title="Send via WhatsApp">
      {loading ? <div className="animate-spin w-4 h-4 border-2 border-green-600 border-t-transparent rounded-full" /> : <MessageCircle size={18} />}
    </button>
  );
}
