import React, { useState } from "react";
import {
  Bot,
  FileSpreadsheet,
  CheckCircle2,
  AlertTriangle,
  Send,
  Sparkles,
  Search,
  ShoppingCart,
  ArrowRight,
  HelpCircle,
  Edit2,
  RefreshCw,
  Eye,
  Building2,
  Tag,
  Check,
  Headphones,
  Smartphone,
  MessageSquare,
  List
} from "lucide-react";

export default function CustomerAiOnboardingPage() {
  // Mobile Active Tab Selector (on small screens)
  const [mobileActiveTab, setMobileActiveTab] = useState("items"); // 'items' | 'chat' | 'preview'

  // Live Draft Items generated by AI for the Customer
  const [draftItems, setDraftItems] = useState([
    {
      id: 1,
      name: "Berger Walmasta White 20L",
      category: "Exterior Emulsion",
      hsn: "3209",
      gst: 18,
      stockQty: 8,
      mrp: 4250,
      costPrice: 2812.50,
      sellingPrice: 3400.00,
      unit: "Bucket",
      status: "READY"
    },
    {
      id: 2,
      name: "Berger Bison Acrylic Emulsion 10L",
      category: "Interior Emulsion",
      hsn: "3209",
      gst: 18,
      stockQty: 12,
      mrp: 2400,
      costPrice: 1590.00,
      sellingPrice: 1950.00,
      unit: "Bucket",
      status: "READY"
    },
    {
      id: 3,
      name: "Astral CPVC Pipe 1 Inch (10 Ft)",
      category: "Pipes & Fittings",
      hsn: "3917",
      gst: 18,
      stockQty: 40,
      mrp: 550,
      costPrice: 340.00,
      sellingPrice: 420.00,
      unit: "Piece",
      status: "READY"
    }
  ]);

  // Selected item for Live Billing Search Preview
  const [previewItem, setPreviewItem] = useState(draftItems[0]);
  const [billingSearchQuery, setBillingSearchQuery] = useState("walmasta 20");

  // Customer AI Chat Conversation
  const [messages, setMessages] = useState([
    {
      sender: "ai",
      text: "नमस्ते राजेश जी! 🙏 मैंने आपके पर्चे से 3 मुख्य आइटम्स का स्टॉक तैयार किया है। नीचे दिए गए कार्ड्स में चेक करें।\n\nअगर किसी आइटम का रेट या स्टॉक बदलना है, तो मुझे बस यहाँ लिखकर या बोलकर बता दें!"
    }
  ]);

  const [customerInput, setCustomerInput] = useState("");
  const [isAiTyping, setIsAiTyping] = useState(false);
  const [isSavedLive, setIsSavedLive] = useState(false);

  // Handle Customer Chat with AI for dynamic corrections
  const handleCustomerSendMessage = (e) => {
    if (e) e.preventDefault();
    if (!customerInput.trim()) return;

    const userMsg = customerInput.trim();
    setMessages((prev) => [...prev, { sender: "user", text: userMsg }]);
    setCustomerInput("");
    setIsAiTyping(true);

    setTimeout(() => {
      if (userMsg.toLowerCase().includes("walmasta") || userMsg.toLowerCase().includes("3500") || userMsg.toLowerCase().includes("10")) {
        setDraftItems((prev) =>
          prev.map((item) =>
            item.id === 1
              ? { ...item, sellingPrice: 3500.0, stockQty: 10 }
              : item
          )
        );
        setPreviewItem((prev) =>
          prev.id === 1 ? { ...prev, sellingPrice: 3500.0, stockQty: 10 } : prev
        );
        setMessages((prev) => [
          ...prev,
          {
            sender: "ai",
            text: "✅ बिल्कुल राजेश जी! मैंने 'Berger Walmasta White 20L' का सेलिंग प्राइस ₹3,500 और स्टॉक 10 बाल्टी अपडेट कर दिया है। '💡 बिलिंग प्रीव्यू' टैब में देखें कि काउंटर पर यह कैसा दिखेगा!"
          }
        ]);
      } else {
        setMessages((prev) => [
          ...prev,
          {
            sender: "ai",
            text: `✅ मैंने आपके निर्देश ("${userMsg}") के अनुसार स्टॉक में बदलाव कर दिया है!`
          }
        ]);
      }
      setIsAiTyping(false);
    }, 1000);
  };

  const handleConfirmAndSaveAll = () => {
    setIsSavedLive(true);
  };

  const handleEscalateToOwner = () => {
    alert("📲 आपकी रिक्वेस्ट और चैट हमारे मुख्य सपोर्ट हेड (मालिक) को भेज दी गई है। वे इसे 5 मिनट में रिव्यू करके अप्रूव कर देंगे!");
  };

  return (
    <div className="p-3 md:p-6 max-w-7xl mx-auto space-y-4 md:space-y-6 animate-in fade-in pb-20 md:pb-6">
      {/* Top Welcome Header */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-purple-950 p-4 md:p-6 rounded-2xl md:rounded-3xl text-white shadow-xl flex flex-col md:flex-row justify-between md:items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2.5 md:p-3.5 bg-gradient-to-tr from-indigo-500 to-purple-600 rounded-xl md:rounded-2xl shadow-lg">
            <Bot className="w-6 h-6 md:w-8 md:h-8 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-lg md:text-2xl font-black">AI स्टॉक असिस्टेंट</h1>
              <span className="text-[10px] bg-emerald-400 text-slate-950 px-2 py-0.5 rounded-full font-black">
                Mobile & Web 📱
              </span>
            </div>
            <p className="text-[11px] md:text-xs text-indigo-200">
              AI से बोलकर रेट बदलें और देखें कि बिल में कैसा दिखेगा
            </p>
          </div>
        </div>

        <button
          onClick={handleEscalateToOwner}
          className="px-3 py-1.5 bg-white/10 hover:bg-white/20 border border-white/20 rounded-xl text-xs font-bold text-indigo-200 flex items-center justify-center gap-1.5 transition"
        >
          <Headphones size={14} /> 🆘 मालिक से मदद लें
        </button>
      </div>

      {/* Mobile-Only Navigation Tabs (< md screens) */}
      <div className="flex md:hidden bg-slate-100 p-1 rounded-2xl border text-xs font-bold">
        <button
          onClick={() => setMobileActiveTab("items")}
          className={`flex-1 py-2 rounded-xl flex items-center justify-center gap-1.5 transition ${
            mobileActiveTab === "items" ? "bg-indigo-600 text-white shadow" : "text-slate-600"
          }`}
        >
          <List size={14} /> ड्राफ्ट आइटम्स ({draftItems.length})
        </button>
        <button
          onClick={() => setMobileActiveTab("chat")}
          className={`flex-1 py-2 rounded-xl flex items-center justify-center gap-1.5 transition ${
            mobileActiveTab === "chat" ? "bg-indigo-600 text-white shadow" : "text-slate-600"
          }`}
        >
          <MessageSquare size={14} /> AI चैट
        </button>
        <button
          onClick={() => setMobileActiveTab("preview")}
          className={`flex-1 py-2 rounded-xl flex items-center justify-center gap-1.5 transition ${
            mobileActiveTab === "preview" ? "bg-indigo-600 text-white shadow" : "text-slate-600"
          }`}
        >
          <ShoppingCart size={14} /> प्रीव्यू
        </button>
      </div>

      {isSavedLive ? (
        <div className="p-6 md:p-8 bg-emerald-50 border border-emerald-200 rounded-3xl text-center space-y-3 animate-in zoom-in-95">
          <CheckCircle2 size={48} className="text-emerald-600 mx-auto" />
          <h2 className="text-xl md:text-2xl font-black text-emerald-950">बधाई हो! आपकी दुकान का स्टॉक ऑनलाइन सेव हो गया है 🎉</h2>
          <p className="text-xs text-emerald-800 max-w-md mx-auto">
            आपके {draftItems.length} आइटम्स बिलिंग काउंटर पर तुरंत लाइव हो चुके हैं।
          </p>
          <a
            href="/billing/pos"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs rounded-xl shadow-lg transition"
          >
            <ShoppingCart size={16} /> बिलिंग काउंटर (POS) खोलें →
          </a>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Content Area (Items + Chat) */}
          <div className={`lg:col-span-2 space-y-4 ${mobileActiveTab === 'preview' ? 'hidden md:block' : ''}`}>
            
            {/* Draft Items Section */}
            <div className={`bg-white p-4 md:p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4 ${mobileActiveTab === 'chat' ? 'hidden md:block' : ''}`}>
              <div className="flex justify-between items-center">
                <div>
                  <h3 className="font-black text-sm md:text-base text-slate-900 flex items-center gap-2">
                    <FileSpreadsheet className="text-indigo-600" size={18} /> AI द्वारा तैयार स्टॉक ({draftItems.length} Items)
                  </h3>
                  <p className="text-xs text-slate-500">कार्ड पर टैप करके सेलिंग प्राइस चेक करें</p>
                </div>
              </div>

              {/* Mobile Card List View (Clean & Responsive) */}
              <div className="space-y-3">
                {draftItems.map((item) => (
                  <div
                    key={item.id}
                    onClick={() => {
                      setPreviewItem(item);
                      if (window.innerWidth < 768) setMobileActiveTab("preview");
                    }}
                    className={`p-3.5 rounded-2xl border transition cursor-pointer space-y-2 ${
                      previewItem.id === item.id ? "bg-indigo-50/90 border-indigo-300 shadow-sm" : "bg-slate-50 border-slate-200 hover:bg-white"
                    }`}
                  >
                    <div className="flex justify-between items-start">
                      <div>
                        <span className="text-[10px] bg-white px-2 py-0.5 rounded font-bold text-slate-600 border">
                          {item.category}
                        </span>
                        <h4 className="font-black text-xs md:text-sm text-slate-900 mt-1">{item.name}</h4>
                      </div>
                      <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 font-black text-[10px] rounded-full">
                        स्टॉक: {item.stockQty} {item.unit}
                      </span>
                    </div>

                    <div className="flex justify-between items-center text-xs pt-2 border-t border-slate-200/60 font-mono">
                      <span className="text-slate-400 text-[11px] line-through">MRP: ₹{item.mrp}</span>
                      <span className="text-slate-600 text-[11px]">खरीद: ₹{item.costPrice.toFixed(0)}</span>
                      <span className="font-black text-emerald-600 text-sm">बिक्री: ₹{item.sellingPrice.toFixed(0)}</span>
                    </div>
                  </div>
                ))}
              </div>

              {/* 1-Click Save Button */}
              <button
                onClick={handleConfirmAndSaveAll}
                className="w-full py-3.5 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-black text-xs rounded-2xl shadow-lg transition flex items-center justify-center gap-2"
              >
                <CheckCircle2 size={18} /> सब सही है! 1-क्लिक में दुकान में सेव करें →
              </button>
            </div>

            {/* AI Interactive Chat Section */}
            <div className={`bg-white p-4 md:p-6 rounded-3xl border border-slate-200 shadow-sm space-y-3 ${mobileActiveTab === 'items' ? 'hidden md:block' : ''}`}>
              <h3 className="font-black text-sm text-slate-900 flex items-center gap-2">
                <Sparkles className="text-amber-500" size={16} /> AI से चैट करके बदलाव करवाएं
              </h3>

              <div className="space-y-2 max-h-48 overflow-y-auto p-3 bg-slate-50 rounded-2xl border text-xs">
                {messages.map((m, idx) => (
                  <div key={idx} className={`flex ${m.sender === "user" ? "justify-end" : "justify-start"}`}>
                    <div className={`p-2.5 rounded-2xl max-w-xs md:max-w-sm whitespace-pre-line ${
                      m.sender === "user" ? "bg-indigo-600 text-white font-bold" : "bg-white border text-slate-800 shadow-sm"
                    }`}>
                      {m.text}
                    </div>
                  </div>
                ))}
                {isAiTyping && (
                  <div className="text-[10px] text-indigo-600 font-bold animate-pulse">
                    🤖 AI टाइप कर रहा है...
                  </div>
                )}
              </div>

              <form onSubmit={handleCustomerSendMessage} className="flex gap-2">
                <input
                  type="text"
                  placeholder="उदा: 'Walmasta का रेट ₹3,500 करो'"
                  value={customerInput}
                  onChange={(e) => setCustomerInput(e.target.value)}
                  className="flex-1 p-2.5 border border-slate-300 rounded-xl text-xs outline-none focus:ring-2 focus:ring-indigo-500 font-medium"
                />
                <button
                  type="submit"
                  className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-xl shadow flex items-center gap-1 transition"
                >
                  <Send size={13} />
                </button>
              </form>
            </div>
          </div>

          {/* Right Column: Live Billing Search Preview */}
          <div className={`lg:col-span-1 space-y-4 ${mobileActiveTab !== 'preview' ? 'hidden md:block' : ''}`}>
            <div className="bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 p-5 md:p-6 rounded-3xl text-white shadow-xl space-y-4 border border-indigo-400/20">
              <div className="flex items-center gap-2">
                <ShoppingCart className="text-emerald-400" size={18} />
                <h3 className="font-black text-sm">💡 लाइव बिलिंग सर्च प्रीव्यू</h3>
              </div>
              <p className="text-[11px] text-indigo-200">
                जब आप या आपका स्टाफ काउंटर पर बिल काटेगा, तो यह आइटम ऐसे सर्च होगा:
              </p>

              {/* Mock Search Bar */}
              <div className="bg-white/10 p-2.5 rounded-2xl border border-white/20 flex items-center gap-2">
                <Search size={14} className="text-indigo-300" />
                <input
                  type="text"
                  value={billingSearchQuery}
                  onChange={(e) => setBillingSearchQuery(e.target.value)}
                  className="bg-transparent text-xs font-bold text-white outline-none w-full"
                  placeholder="सर्च करें..."
                />
              </div>

              {/* Mock POS Result Card */}
              <div className="bg-white p-4 rounded-2xl text-slate-900 shadow-2xl space-y-2 border-2 border-emerald-500 animate-in fade-in">
                <div className="flex justify-between items-start">
                  <div>
                    <span className="text-[10px] bg-indigo-100 text-indigo-800 font-bold px-2 py-0.5 rounded">
                      {previewItem.category}
                    </span>
                    <h4 className="font-black text-xs md:text-sm text-slate-900 mt-1">{previewItem.name}</h4>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 font-black text-[10px] rounded-full">
                    Stock: {previewItem.stockQty} {previewItem.unit}
                  </span>
                </div>

                <div className="pt-2 border-t border-slate-100 flex justify-between items-baseline">
                  <div>
                    <span className="text-[10px] text-slate-400 block line-through">MRP: ₹{previewItem.mrp}</span>
                    <span className="text-xs text-slate-600 font-bold">बिक्री दर (Tax Incl.):</span>
                  </div>
                  <span className="text-lg md:text-xl font-black text-emerald-600 font-mono">
                    ₹{previewItem.sellingPrice.toFixed(2)}
                  </span>
                </div>

                <div className="bg-slate-50 p-2 rounded-xl text-[10px] text-slate-500 flex justify-between font-mono">
                  <span>HSN: {previewItem.hsn}</span>
                  <span>GST: {previewItem.gst}%</span>
                  <span>मुनाफा: ~₹{(previewItem.sellingPrice - previewItem.costPrice).toFixed(0)}</span>
                </div>
              </div>

              <div className="text-[11px] text-emerald-300 font-medium bg-emerald-500/10 p-3 rounded-xl border border-emerald-500/20">
                ✓ मोबाइल से भी 0.1 सेकंड में बिल बनेगा और व्हाट्सएप पर इनवॉइस PDF जाएगा!
              </div>

              {/* Back to Items Button on Mobile */}
              <button
                onClick={() => setMobileActiveTab("items")}
                className="w-full md:hidden py-2.5 bg-white/10 text-white rounded-xl text-xs font-bold"
              >
                ← वापस ड्राफ्ट आइटम्स पर जाएं
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
