import React, { useState } from 'react';
import { TouchableOpacity, Linking, Alert, Text, StyleSheet, ActivityIndicator } from 'react-native';
import { postData } from '../services/ApiService';

const WhatsappSender = ({ bill }) => {
  const [loading, setLoading] = useState(false);

  const handleSend = async () => {
    if (!bill.customerMobile) {
      Alert.alert("Error", "Customer mobile number is missing for this bill!");
      return;
    }

    let mobile = bill.customerMobile.replace(/\D/g, "");
    if (mobile.length === 10) {
      mobile = "91" + mobile;
    }

    setLoading(true);
    try {
      // Fetch dynamic message with Payment Link from Backend
      const response = await postData("/whatsapp/send-invoice", {
        billId: bill._id,
        mobileNumber: mobile
      });

      // Use the preview message generated by backend, or fallback to default
      const message = response.data?.preview || response.preview || `Hello ${bill.customerName},\n\nYour invoice *${bill.billNumber || bill.billNo}* for amount *₹${(bill.total || bill.finalAmount || 0).toLocaleString()}* has been generated.\n\nThank you for your business!`;
      
      // Use WhatsApp app deep link
      const url = `whatsapp://send?phone=${mobile}&text=${encodeURIComponent(message)}`;

      const supported = await Linking.canOpenURL(url);
      if (supported) {
        await Linking.openURL(url);
      } else {
        Alert.alert("Not Installed", "WhatsApp is not installed on your device.");
      }
    } catch (error) {
      console.error("An error occurred", error);
      Alert.alert("Error", "Failed to generate WhatsApp link. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <TouchableOpacity onPress={handleSend} style={styles.button} disabled={loading}>
      {loading ? (
        <ActivityIndicator size="small" color="#16a34a" />
      ) : (
        <Text style={styles.text}>💬 Send WA</Text>
      )}
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  button: {
    backgroundColor: '#dcfce7', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6,
  },
  text: { color: '#16a34a', fontWeight: 'bold', fontSize: 13 },
});

export default WhatsappSender;