-- company_users junction table (Many-to-Many relationship between users and companies)
CREATE TABLE company_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member', -- 'admin', 'owner', 'member', 'accountant'
    
    created_at TIMESTAMPTZ DEFAULT now(),

    -- Ek user ek company me ek hi role me ho sakta hai
    UNIQUE(user_id, company_id)
);

-- RLS for company_users table
ALTER TABLE company_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to see their own membership"
ON company_users FOR SELECT
USING (user_id = auth.uid());