-- party_transactions table (Ledger for each party)
CREATE TABLE party_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    party_id UUID NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    
    date TIMESTAMPTZ NOT NULL,
    details TEXT,
    
    -- Debit/Credit
    debit NUMERIC(12, 2) DEFAULT 0.00,
    credit NUMERIC(12, 2) DEFAULT 0.00,
    
    type TEXT, -- 'bill', 'payment', 'opening_balance', 'manual'
    
    -- Link to the original bill/purchase if applicable
    sale_id UUID REFERENCES sales(id) ON DELETE SET NULL,
    purchase_id UUID REFERENCES purchases(id) ON DELETE SET NULL,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS for party_transactions table
ALTER TABLE party_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own company's transactions"
ON party_transactions FOR ALL
USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid()));