-- stock_adjustments table
CREATE TABLE stock_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    date TIMESTAMPTZ DEFAULT now(),
    type TEXT NOT NULL, -- 'addition' or 'reduction'
    quantity NUMERIC(10, 3) NOT NULL,
    
    reason TEXT,
    notes TEXT,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS for stock_adjustments table
ALTER TABLE stock_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own company's stock adjustments"
ON stock_adjustments FOR ALL
USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid()));