-- security_logs table
-- This table logs important security events like login attempts, app starts, etc.
CREATE TABLE security_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID REFERENCES companies(id) ON DELETE SET NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

    event_type TEXT NOT NULL, -- e.g., 'APP_STARTED', 'LOGIN_SUCCESS', 'LOGIN_FAILURE'
    ip_address TEXT,
    user_agent TEXT,
    details JSONB,

    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS for security_logs table
ALTER TABLE security_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service_role to insert security logs"
ON security_logs FOR INSERT
WITH CHECK (true);