import React, { useState, useEffect } from "react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";
import { TrendingUp, Users, Award, DollarSign, Star, HeartHandshake } from "lucide-react";
import api from "../../services/api";
import Loader from "../../components/Loader";

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#6366f1'];

export default function StaffPerformancePage() {
  const [staffData, setStaffData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [kpis, setKpis] = useState({ totalStaff: 0, totalRevenue: 0, topPerformer: 'N/A' });

  useEffect(() => {
    const fetchPerformanceData = async () => {
      setLoading(true);
      try {
        const res = await api.get("/api/reports/staff-performance");
        const performanceData = res.data || [];
        setStaffData(performanceData);

        // Calculate KPIs
        const totalRevenue = performanceData.reduce((sum, staff) => sum + staff.revenue, 0);
        const topPerformer = performanceData.length > 0 ? performanceData.reduce((prev, current) => (prev.revenue > current.revenue) ? prev : current) : { name: 'N/A' };
        
        setKpis({
          totalStaff: performanceData.length,
          totalRevenue: totalRevenue,
          topPerformer: topPerformer.name
        });

      } catch (error) {
        console.error("Failed to fetch staff performance:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchPerformanceData();
  }, []);

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-2">
            <TrendingUp className="text-blue-600" /> Staff Performance Dashboard
          </h1>
          <p className="text-gray-600 mt-1">Track sales, revenue, and targets of your team members visually.</p>
        </div>
      </div>

      {loading && <Loader />}

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center gap-4">
          <div className="p-3 bg-blue-100 text-blue-600 rounded-lg"><Users size={24} /></div>
          <div><p className="text-sm text-gray-500 font-medium">Total Active Staff</p><p className="text-2xl font-bold text-gray-900">{kpis.totalStaff}</p></div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center gap-4">
          <div className="p-3 bg-green-100 text-green-600 rounded-lg"><DollarSign size={24} /></div>
          <div><p className="text-sm text-gray-500 font-medium">Total Revenue Generated</p><p className="text-2xl font-bold text-gray-900">₹{(kpis.totalRevenue / 100000).toFixed(2)}L</p></div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex items-center gap-4">
          <div className="p-3 bg-orange-100 text-orange-600 rounded-lg"><Award size={24} /></div>
          <div><p className="text-sm text-gray-500 font-medium">Top Performer</p><p className="text-lg font-bold text-gray-900">{kpis.topPerformer}</p></div>
        </div>
        <div className="bg-white p-5 rounded-xl shadow-sm border border-amber-100 flex items-center gap-4">
          <div className="p-3 bg-amber-100 text-amber-600 rounded-lg"><Star size={24} className="fill-amber-500 text-amber-500" /></div>
          <div><p className="text-sm text-gray-500 font-medium">Avg Customer CSAT</p><p className="text-2xl font-black text-amber-600">4.8 / 5 ⭐</p></div>
        </div>
      </div>

      {!loading && staffData.length > 0 && <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Graph 1: Revenue by Staff */}
        <div className="col-span-2 bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-bold text-gray-800 mb-6">Revenue Generated by Staff (₹)</h3>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={staffData} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis axisLine={false} tickLine={false} tickFormatter={(value) => `₹${value / 1000}k`} />
                <Tooltip cursor={{ fill: 'transparent' }} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} formatter={(value) => `₹${value.toLocaleString()}`} />
                <Legend />
                <Bar dataKey="revenue" name="Total Revenue (₹)" fill="#3b82f6" radius={[4, 4, 0, 0]} barSize={40} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Graph 2: Bills Handled (Pie Chart) */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-bold text-gray-800 mb-2">Invoices Handled Share</h3>
          <p className="text-sm text-gray-500 mb-6">Who created the most bills?</p>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={staffData} cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="bills" nameKey="name">
                  {staffData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend verticalAlign="bottom" height={36} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>}

      {/* Detailed Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-gray-50">
            <tr>
              <th className="p-4 font-semibold text-gray-600">Staff Name</th>
              <th className="p-4 font-semibold text-gray-600 text-center">Bills Created</th>
              <th className="p-4 font-semibold text-gray-600 text-right">Revenue Generated</th>
              <th className="p-4 font-semibold text-gray-600 text-center">Target Achieved</th>
              <th className="p-4 font-semibold text-gray-600 text-center">Customer Rating (CSAT)</th>
            </tr>
          </thead>
          <tbody>
            {!loading && staffData.length === 0 && (
              <tr><td colSpan="4" className="p-8 text-center text-gray-500">No performance data available.</td></tr>
            )}
            {staffData.map((staff, idx) => {
              const targetAchieved = staff.salesTarget > 0 ? Math.min(100, (staff.revenue / staff.salesTarget) * 100) : 0;
              return (
              <tr key={idx} className="border-t border-gray-100 hover:bg-gray-50">
                <td className="p-4 font-medium text-gray-900">{staff.name}</td>
                <td className="p-4 text-center text-gray-700">{staff.bills}</td>
                <td className="p-4 text-right font-bold text-gray-900">₹{staff.revenue.toLocaleString()}</td>
                <td className="p-4">
                  <div className="w-full bg-gray-200 rounded-full h-2.5 mt-1">
                    <div className={`h-2.5 rounded-full ${targetAchieved >= 90 ? 'bg-green-500' : targetAchieved >= 70 ? 'bg-blue-500' : 'bg-orange-500'}`} style={{ width: `${targetAchieved}%` }}></div>
                  </div>
                  <p className="text-xs text-center mt-1 text-gray-500">{targetAchieved.toFixed(1)}%</p>
                </td>
              </tr>);
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}