import React, { useState } from "react";
import { MessageCircle } from "lucide-react";
import api from "../services/api"; // Fixed import path

export default function WhatsappSender({ bill }) {
  const [loading, setLoading] = useState(false);

  const handleSend = async () => {
    if (!bill.customerMobile) {
      alert("Customer mobile number is missing for this bill!");
      return;
    }

    setLoading(true);
    try {
      let mobile = bill.customerMobile.replace(/\D/g, "");
      if (mobile.length === 10) mobile = "91" + mobile;

      // Generate a Live Tracking Link for the bill
      const liveBillLink = `${window.location.origin}/bill/view/${bill._id || bill.id}`;

      // Fetch dynamic message with Payment Link from Backend
      const response = await api.post("/api/whatsapp/send-invoice", {
        billId: bill._id,
        mobileNumber: mobile
      });

      // Use the preview message generated by backend, or fallback to default with Live Link
      const message = response.data?.preview || response.preview || `Hello ${bill.customerName},\n\nYour invoice *${bill.billNumber || bill.billNo}* for amount *₹${(bill.total || bill.finalAmount || 0).toLocaleString()}* has been generated.\n\n📄 *View/Download Latest Bill here:*\n${liveBillLink}\n\nThank you for your business!`;

      // 1. Try background send if Electron WhatsApp is connected (Vyapar Style)
      if (window.electron && window.electron.whatsapp) {
        const waStatus = await window.electron.whatsapp.getStatus();
        if (waStatus === 'connected') {
          await window.electron.whatsapp.sendMessage(mobile, message);
          alert("Bill sent automatically via Background WhatsApp!");
          setLoading(false);
          return; // Exit function so it doesn't open the browser
        }
      }

      // 2. Fallback: If not linked, open standard WhatsApp Web/App Link
      const url = `https://wa.me/${mobile}?text=${encodeURIComponent(message)}`;
      window.open(url, "_blank");
    } catch (error) {
      console.error("Failed to generate WhatsApp message", error);
      alert("Failed to generate WhatsApp link. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button type="button" onClick={handleSend} disabled={loading} className="p-2 hover:bg-green-100 rounded-lg text-green-600 transition disabled:opacity-50" title="Send via WhatsApp">
      {loading ? <div className="animate-spin w-4 h-4 border-2 border-green-600 border-t-transparent rounded-full" /> : <MessageCircle size={18} />}
    </button>
  );
}